export const BASE_URL = 'http://localhost:3000/api';
export const AUTH_TOKEN = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJtdXNpY3BsYXlpbiIsInN1YiI6IjVhYWQwZDFlMjYxNDk4MWRjNGJlYmY2MCIsImlhdCI6MTUyMTI5MDUzNTAyMCwiZXhwIjoxNTIxMzc2OTM1MDIwfQ.nESlTMP5oQ4pzg-N8fueN6I9B5p8Ot54VDyzRy-3rmo';
